### ISSUE TITLE
readme有点小问题

### ISSUE THREAD

**Issue by weearc** [noahsai/tianqi#1]
那个qmake ..是不是应该去掉一个 .

**Comment by weearc** [comment]
另外要是可以随意选择置顶还是置于底层就好了

**Comment by noahsai** [comment]
没错的，我的意思是在源码目录建立bulid文件夹，然后在这个文件夹里qmake，这样可以隔离编译文件和源码文件。另外置顶功能在我的系统有问题，而且觉得很鸡肋，所以已经去除了。
